### ISSUE TITLE
Crash when shift clicking constellation paper into inventory

### ISSUE THREAD

**Issue by BrisingrAerowing** [HellFirePvP/AstralSorcery#656] opened 2018-04-26 02:27 UTC
[Crash Log](https://gist.github.com/BrisingrAerowing/9ac3fcf5e3f6b8374107c8afb716fa14)

AS: 1.8.8
Forge: 2673
MC: 1.12.2

**Comment by BrisingrAerowing** [comment] 2018-04-26 02:31
It looks like [this line](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchManager.java#L373) is the issue. The other methods in that class use getProgress to guard against the progress not being loaded.

**Comment by HellFirePvP** [comment] 2018-04-26 03:38
Then look 1 step *before* that. It is guarded against...
https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/data/research/ResearchManager.java#L237-L246

**Comment by HellFirePvP** [comment] 2018-05-06 19:57
Well, does this seem to persist? I can't really see how this happens and/or reproduce it either...

**Comment by BrisingrAerowing** [comment] 2018-05-07 02:01
It happens randomly. I haven't seen it happen (yet) when I actually pick up the item, or when I break the chest and collect it from the ground. Just when I shift-click. Which makes it even more bizarre.

**Comment by Hyperion505** [comment] 2018-06-22 02:54
This has also happened to me just now, except now I crash to desktop before my world even finishes loading. All after shift clicking my first Constellation paper.
[Crash Report](https://github.com/HellFirePvP/AstralSorcery/files/2126149/crash-2018-06-21_22.50.55-server.txt)

**Comment by Doomgull** [comment] 2018-06-22 09:59
While the initial trigger is the same, the resulting successive crashes are not remotely the same issue, Hyperion. Delete your <uuid>.astral file in the player data, it's corrupt.

If you have a log from the initial crash, instead, would be useful.

**Comment by Hyperion505** [comment] 2018-06-22 12:56
I can get you that, currently at work so I'll post it when I get home.

**Comment by BrisingrAerowing** [comment] 2018-06-22 19:49
I did some testing and found that Forge 2673 (what I was on at the time) has this happen, but 2705 (what I'm on now) doesn't. I'm going to chalk this up to a weird Forge quirk.

**Comment by Hyperion505** [comment] 2018-06-22 21:02
I know this was just closed but this is for @Doomgull here is that preliminary crash log.

[Preliminary Crash Log](https://github.com/HellFirePvP/AstralSorcery/files/2129136/crash-2018-06-21_22.41.13-server.txt)

**Comment by BrisingrAerowing** [comment] 2018-06-24 01:03
I'll go ahead and reopen this then.

**Comment by diablo184** [comment] 2018-07-06 03:39
i just had this happen to me on a server i started is there a fix for this i can not rejoin the server currently

**Comment by Doomgull** [comment] 2018-07-06 10:13
@diablo184 have your player data for AS reset, by removing the <uuid>.astral file from the player data directory.

**Comment by diablo184** [comment] 2018-07-06 20:54
that got me back in but every time i pick up the papers i crash no matter how i get them

**Comment by Doomgull** [comment] 2018-07-06 21:06
Can you pastebin one of your client crashes?

And then use the /as commands to try adding one instead.

**Comment by diablo184** [comment] 2018-07-06 21:19
this happened after trying to add one through creative mode 
[latest.log](https://github.com/HellFirePvP/AstralSorcery/files/2171999/latest.log)

**Comment by HellFirePvP** [comment] 2018-07-06 21:40
Also interesting there:
> [16:16:48] [Server thread/WARN] [Astral Sorcery]: [AstralSorcery] Failed to load AstralSocery Progress data for diablo184
[16:16:48] [Server thread/WARN] [Astral Sorcery]: [AstralSorcery] Erroneous file: 59575435-e498-4fb4-8a72-dfc1d9a7b7a0.astral

**Comment by Doomgull** [comment] 2018-07-06 21:40
Browsing it on mobile:

"[16:16:48] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Synchronizing configuration to diablo184
[16:16:48] [Server thread/WARN] [Astral Sorcery]: [AstralSorcery] Failed to load AstralSocery Progress data for diablo184
[16:16:48] [Server thread/WARN] [Astral Sorcery]: [AstralSorcery] Erroneous file: 59575435-e498-4fb4-8a72-dfc1d9a7b7a0.astral"

Make sure that the player data files for the astral progression are not write protected, and that they are not unwritable by other users in that directory.

**Comment by diablo184** [comment] 2018-07-06 21:57
how would i fix that?

**Comment by diablo184** [comment] 2018-07-06 21:57
or should i do an earlier version?

**Comment by diablo184** [comment] 2018-07-06 22:06
now my astral book tabs are gone='(

**Comment by Doomgull** [comment] 2018-07-06 23:13
None of it should be read-only. How will it update and change the file if it cannot write to it?

That entire world-data directory should be read/write for all users, and inherited down through children, tbh.

**Comment by diablo184** [comment] 2018-07-10 04:00
is there a command to give myself the constellations in the journal

**Comment by Doomgull** [comment] 2018-07-10 09:33
Can you provide that output?

And, again, have the file permissions been corrected for the directory and files to allow writes?

**Comment by Doomgull** [comment] 2018-07-20 09:32
The additional issues not solved with the Forge version change were due to More Commands doing something weird. Closing this out as housecleaning after the other ticket was archived.

**Closed by Doomgull** 2018-07-20 09:32 UTC
Labels: bug, uuuhhhh.... wtf.
