### ISSUE TITLE
Formation Wand + Storage Drawers = Crash

### ISSUE THREAD

**Issue by Lejoni** [HellFirePvP/AstralSorcery#1522] opened 2020-12-04 10:46 UTC
When ghosts from Formation Wand touches an (Oak) Storage Drawer (from Storage Drawer mod) client crash.

Very easy to reproduce:
Creative world.
Place down a oak storage drawer 1x1
Get formation wand and select horizontal plane and select grass block.
Move ghosts towards storage drawer so the ghosts touch the drawer.
[crash-2020-12-04_11.41.10-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/5642157/crash-2020-12-04_11.41.10-client.txt)

Should add I use Optifine. But I also tried with optifine disabled, and it still crashed.
This is quite critical, sins only way to recover from this is to load a backup, as you are in the exact same position as soon as you reload the save.

**Comment by HellFirePvP** [comment] 2020-12-04 11:34
Duplicate of #1418

**Closed by HellFirePvP** 2020-12-04 11:34 UTC
