### ISSUE TITLE
(1.12.2) Incompatibility with InWorldCrafting.

### ISSUE THREAD

**Issue by puncrafter** [HellFirePvP/AstralSorcery#1352] opened 2020-08-19 04:44 UTC
I'm not sure which mod is causing this issue, so I'm posting this issue to both Astral Sorcery and InWorldCrafting's issue pages.

Forge Version: 14.23.5.2847
Astral Sorcery Version: 1.12.2-1.10.22
InWorldCrafting Version: 1.12.2-0.13.0

I have made recipes using InWorldCrafting that use Liquid Starlight as a fluid catalyst for the recipe. For some reason, this causes Celestial Crystal growth to not function. I can still grow Dynamism Gems, but Celestial Crystal Clusters won't form. Below I'll paste my InWorldCrafting script if that helps.

`// In-World Crafting`
` `
`// Get Yer Imports!`
` `
`import mods.inworldcrafting.FluidToItem;`
` `
`// Liquid Starlight`
` `
`FluidToItem.transform(<minecraft:iron_ingot>, <liquid:astralsorcery.liquidstarlight>, <minecraft:gold_ingot>, false);`
`FluidToItem.transform(<astralsorcery:itemcraftingcomponent:2>, <liquid:astralsorcery.liquidstarlight>, <contenttweaker:iron_dust>, false);`
`FluidToItem.transform(<minecraft:redstone>, <liquid:astralsorcery.liquidstarlight>, <arcanearchives:radiant_dust>, false);`
`FluidToItem.transform(<minecraft:glowstone_dust>, <liquid:astralsorcery.liquidstarlight>, <contenttweaker:gold_dust>, false);`
`FluidToItem.transform(<minecraft:prismarine_crystals>, <liquid:astralsorcery.liquidstarlight>, <minecraft:prismarine_shard>, false);`
`FluidToItem.transform(<minecraft:quartz>, <liquid:astralsorcery.liquidstarlight>, <arcanearchives:raw_quartz>, false);`
`FluidToItem.transform(<contenttweaker:enchanted_clock>, <liquid:astralsorcery.liquidstarlight>, <minecraft:clock>, false);`
`FluidToItem.transform(<minecraft:diamond>, <liquid:astralsorcery.liquidstarlight>, <minecraft:dye:4>, false);`
` `
`// Water`
` `
`FluidToItem.transform(<contenttweaker:white_dye>, <liquid:water>, <minecraft:sugar>, false);`
`FluidToItem.transform(<extrautils2:ingredients:14>, <liquid:water>, <astralsorcery:itemcraftingcomponent:2>, false);`
`FluidToItem.transform(<minecraft:dye:11>, <liquid:water>, <minecraft:glowstone_dust>, false);`
`FluidToItem.transform(<minecraft:dye:1>, <liquid:water>, <minecraft:redstone>, false);`
`FluidToItem.transform(<contenttweaker:black_dye>, <liquid:water>, <contenttweaker:charcoal_dust>, false);`

**Comment by Doomgull** [comment] 2020-08-19 13:31
If it works in AS normally, but not here, I'd wager this needs a review by the InWorldCrafting devs to figure out what the issue is. What's the ticket number on their side for linking?

**Comment by puncrafter** [comment] 2020-08-19 18:54
The number is #34.

**Comment by Doomgull** [comment] 2020-08-19 23:53
Closing since the issue was solved on the inworldcrafting side over a year and a half ago.

And I second the statement: use the latest release, don't open tickets for old old versions.

**Closed by Doomgull** 2020-08-19 23:53 UTC
Labels: Not my mod, mod interaction
