### ISSUE TITLE
Altar takes whole tank

### ISSUE THREAD

**Issue by Grzesiu447** [HellFirePvP/AstralSorcery#1640] opened 2021-01-11 07:44 UTC
I was rerolling Resplendent Prism, when I though about using Mekanism tank instead of a bucket, so I don't have to replace them every time.
It worked, but it took the whole tank, contents and the item itself.

Modpack: Valhelsia 3 - verison 3.1.4

**Comment by Algester** [comment] 2021-01-15 09:49
DO NOT USE MEK's TANK it won't be fixed I already asked they wont make sure the tank gives up 1 bucket's worth of fluid for every itteration you may want to try using IE's Jerry Can... know what I might just attempt to do it

good news Jerry Can from Immersive engineering will give up 1bucket's worth of fluid when using it as a bucket Thermal Expansion's Fluid Cell is next

fluid cell however is not acting as a bucket in this instance... so Jerry Cans might be an option

**Comment by Grzesiu447** [comment] 2021-01-15 15:57
Now I also tested Black hole tank from Industrial Foregoing, same problem as with Mekanism tank.
I hope no one uses their Supreme black hole tank, it's a pain to make it.

**Comment by Algester** [comment] 2021-01-15 17:48
Its most likely due to the fact these tanks while can act like buckets they don't give back fluids like buckets case in point a basic mekanism tank will only get 300mB of fluid if treated as a bucket so it wont be useful as a bucket until its at elite tier where it can get 1200 mB when used as such

I'll wait when Thermal gets its reservoir back as that I think I know works as intended also massive amounts of fluid storage

**Comment by Grzesiu447** [comment] 2021-01-15 21:09
> point a basic mekanism tank will only get 300mB of fluid if treated as a bucket so it wont be useful as a bucket until its at elite tier where it can get 1200 mB when used as such

I have no idea, what you are trying to say here. (would be easier if you used commas)
You're saying something about amounts of fluid, while the biggest problem with this bug, are the tanks that get erased from existence. You put your (pretty expensive) ultimate portable tank in the crafting altar, and when it's done crafting, the tank is gone. (Tank as an item, not just fluid in it)

**Comment by Algester** [comment] 2021-01-15 23:44
> 
> 
> > point a basic mekanism tank will only get 300mB of fluid if treated as a bucket so it wont be useful as a bucket until its at elite tier where it can get 1200 mB when used as such
> 
> I have no idea, what you are trying to say here. (would be easier if you used commas)
> You're saying something about amounts of fluid, while the biggest problem with this bug, are the tanks that get erased from existence. You put your (pretty expensive) ultimate portable tank in the crafting altar, and when it's done crafting, the tank is gone. (Tank as an item, not just fluid in it)

I already posted the Issue in mekanism git but it will not be fixed as these tiems do not check Volume perbucket

in BluSunrize's words
As far as I can tell, Mekanism's tank items do not implement getContainerItem.
They should totally do that, and reduce their stored fluid by BUCKET_VOLUME. Report to Mekanism please.

this is the underlying issue so if you need to craft the resplendent prism you need an item that gives off 1 bucket's worth of fluid when used as a bucket mechanic in this case the Jerry Can from IE pretty much does that I dont remember blackhole tanks being used as buckets.... hmmm PneumaticCraft has tanks that work but I do not know which of the 2 tank/bucket tiems work in this case

@HellFirePvP
https://github.com/BluSunrize/ImmersiveEngineering/pull/4474 this might be a relative fix for this issue then

**Closed as completed** 2021-05-23 21:15 UTC
Labels: Type: Bug, Resolution: Fixed/Added next update, Version: 1.16.X
