### ISSUE TITLE
Self attuning isn't working.

### ISSUE THREAD

**Issue by Retty227** [HellFirePvP/AstralSorcery#517] opened 2018-01-21 22:22 UTC
I'm playing on a DW20 server and have passed the point where i should be able to attune to one of the constellations, however the ritual does not start. I am able to attune items and such but not myself. The server said they aren't blocking the ritual and that its probably a bug with the mod. Any Help?

**Comment by Doomgull** [comment] 2018-01-21 22:58
You can't attune to Dim constellations, only the five majors. If it works for crystals, but not yourself, and you're not attuned, it's because you're trying to self-attune to an invalid constellation.

**Comment by Retty227** [comment] 2018-01-21 23:05
I know you cant attune to the dim constellations and have tried the major 5

**Comment by Doomgull** [comment] 2018-01-21 23:09
Do you have a "Perks" tab in the Tome? Which constellation specifically are you looking at? What does it do when you go to step in? Does it lock the camera control and start the attunement? Are the lasers present?

**Comment by Retty227** [comment] 2018-01-21 23:12
there is no perks tab, i have tried all the main 5, it doesn't do anything when i step in, and yes the lasers are present.

**Comment by HellFirePvP** [comment] 2018-01-21 23:16
Did you actually trace and discover the constellation?

**Comment by Retty227** [comment] 2018-01-21 23:17
yep, i saw somewhere that you aren't able to see the other ones if you haven't attuned yourself, is that true?

**Comment by HellFirePvP** [comment] 2018-01-21 23:20
You are only able to find constellation papers of all 12 if you have attuned yourself at least once yes.

**Comment by Retty227** [comment] 2018-01-21 23:21
I have found the other constellation papers already

**Comment by Retty227** [comment] 2018-01-21 23:22
but have never attuned myself

**Comment by HellFirePvP** [comment] 2018-01-21 23:22
Then someone has given you those papers or you've got the knowledge on other ways. They are not obtainable until you've attuned yourself.

**Comment by Retty227** [comment] 2018-01-21 23:23
i was going through the book myself, I'm also the only one in my group doing the mod, i found all the papers in chest from the monuments.

**Comment by Doomgull** [comment] 2018-01-21 23:58
"Discovering means you have to actually trace it in a telescope."

Again, this is not a bug. If you need actual help resolving this, please use the appropriate channel for the mod in the Astral Sorcery Discord server, there are plenty of people available to assist if you provide a screenshot of what they ask.

**Closed by Doomgull** 2018-01-21 23:58 UTC
Labels: User error
