### ISSUE TITLE
Can't attune Mantle of Stars

### ISSUE THREAD

**Issue by jacksonwelsh** [HellFirePvP/AstralSorcery#1804] opened 2021-05-13 07:36 UTC
I'm trying to attune the Mantle of Stars to Vicio and can't seem to get it working. It shows as "ready to craft" in the table but the crafting music barely starts and nothing happens when I right-click it with the resonant wand. 

This is in the Valhelsia 3 modpack on 1.16.5.

**Comment by Jeuvke** [comment] 2021-05-15 20:40
Duplicate of #1622.

**Closed as completed** 2021-05-24 11:06 UTC
