### ISSUE TITLE
[Mod Interaction] Astral Sorcery Attunement stops Pneumaticcraft armor from working

### ISSUE THREAD

**Issue by Duckapple** [HellFirePvP/AstralSorcery#1294] opened 2020-05-26 14:32 UTC
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2847

### Mod Version
1.10.22
*PneumaticCraft: Repressurised* - 1.12.2-0.11.14-395

### Describe your problem, including steps to reproduce it
I use pneumaticcraft armor to fly around and get movement speed and such, but as soon as I completed the Astral Sorcery Attunement ritual for my player character, the pneumaticcraft armor didn't give any of my benefits.

### Any other comments?
**This problem can be fixed by saving the world and reloading it**, but I wanted to report the bug anyways.
I have also submitted this issue to the PNC Github, link [here](https://github.com/TeamPneumatic/pnc-repressurized/issues/505).

**Comment by Doomgull** [comment] 2020-05-26 14:35
Did you try removing and rewearing the armor? AS doesn't change anything there.

**Comment by Duckapple** [comment] 2020-05-26 14:38
Yes, the problem persisted even though I un- and re-equipped my leggings and boots. The armor pieces did not load in the way they usually do when re-equipping (with a progress bar and such), and the effects were still not active.

**Comment by Doomgull** [comment] 2020-08-19 13:36
Closing this since the Pneumaticcraft devs don't want to support/investigate on that MC release.

**Closed by Doomgull** 2020-08-19 13:36 UTC
Labels: mod interaction, wont fix/not my issue

**Comment by NielsPilgaard** [comment] 2021-06-06 05:39
This issue has re-emerged on 1.16.5 :)
https://github.com/NillerMedDild/Enigmatica6/issues/2362
Edit: It hasn't after all :P a reload fixed it, and it's not consistently reproducible.
