### ISSUE TITLE
[1.1.5-beta] NPE Server crash caused by Floating Crystals (TileCollectorCrystal)

### ISSUE THREAD

**Issue by JaSpr** [HellFirePvP/AstralSorcery#61] opened 2017-03-11 18:08 UTC
Astral Sorcery was recently added to All The Mods modpack.  We've had 10 crashes so far this morning by players exploring and coming within range of Astral Sorcery shrines.  The actual blocks causing the crash are the Floating Crystals within the shrines. 

[Latest crash report](https://gist.github.com/anonymous/f23fca1565ec0c29e7301c6ebc62d497)

AS: 1.1.5-beta
MC: 1.10.2
Forge: 12.18.3.2254
All The Mods 1 version 2.51b

**Comment by Saereth** [comment] 2017-03-11 18:25
Can you reproduce this error without Sponge?

**Comment by HellFirePvP** [comment] 2017-03-11 18:28
Seems to happen because it's saving & syncing the NBT data out of the tick cycle before the block placement has completed. This is not known to be caused by pure forge servers, so i'd suggest trying that again without sponge.

**Comment by JaSpr** [comment] 2017-03-13 21:39
I can't run our server without sponge, as it's a live (production) server which people play regularly.  Also, it is difficult to reproduce the bug on purpose, although the bug was happening multiple times per day (10 on the day I entered this bug).  We had to remove Astral Sorcery to stabilize the server.

I'd like to report an issue to [SpongeForge's github](https://github.com/SpongePowered/SpongeForge/issues/), but was wondering if you guys could give me some insight on what exactly to report.

**Comment by HellFirePvP** [comment] 2017-03-13 22:35
I'm also not fully understanding the source of this issue.. i'm going to spend some time digging through sponge's code and see if i can find the problem.

For now, i'm afraid i can't adress this instantly, but it should be resolved and fixed by tomorrow and included in the next, soon-ish-releasing update.

**Closed** 2017-03-14 10:31 UTC
Labels: bug, Fixed/Added next update
