### ISSUE TITLE
Minecraft "not responding" when started Astral Sorcery

### ISSUE THREAD

**Issue by tombula77** [HellFirePvP/AstralSorcery#1750] opened 2021-03-12 21:48 UTC
Hello

From some time i can't run Minecraft with Astral Sorcery mod. It's just stop at loading/initializing screen. First time is about 4 months ago when My SevTech Ages stopped working anymore. After many attempts to solve this, I found that Astral Sorcery freeze my game in 100% cases.

Java latest, reinstalled few times. Few different versions of Astral Sorcery and Baubles. 3 Different versions of forge (2847,2854,2855).

Here is log from Minecraft (killed manually)

https://pastebin.com/L9qXV4c2

Mods: AstralSorcer, Baubles.

Tested different Java versions, still nothing. Reinstalled whole game, minecraft "not responding" on Astral Sorcery starting. Tested 1.15.2 for curiosity and ended with the same result.

https://pastebin.com/N4hHF7ds

Any suggestions?

EDIT:

After some further experiments, when i remove astralsorcery/textures/effect folder, game starts. Few of the files seems not related with problem but bigger part can put Minecraft to not responding in last stage before it starts.

**Comment by PocketfulOfGeese** [comment] 2021-03-23 15:35
Sounds like you're running out of memory, to be honest. I can't get to those pastebin files right now due to pastebin issues, but the logs aren't likely to actually contain the cause unless there's a crash involved.

Please provide your java arguments and the amount of memory your system contains.

**Comment by tombula77** [comment] 2021-03-23 17:09
System memory : 16G
Java args : -Xms256M -Xmx4G
Tested also on default minecraft line : -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Mods: AstralSorcer, Baubles.

Screenshot  (Minecraft not responding but this is not Game Crash)

https://i.ibb.co/zhwrc32/astral.png

Few last lines from latest.log

[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Refreshing and Invalidating Resources
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Finished reloading, rebinding textures...
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Preload mandatory textures
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Preload textures

And form debug.log

[17:42:50] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Refreshing and Invalidating Resources
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Finished reloading, rebinding textures...
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Preload mandatory textures
[17:42:51] [Client thread/INFO] [Astral Sorcery]: [AssetLibrary] Preload textures

Memory quantity from task manager on dead (few attempts) : 1238M/1110M/1323M

**Comment by PocketfulOfGeese** [comment] 2021-03-23 18:24
How long did you wait for it before killing it when Windows said it was non-responsive? Windows is known to be overzealous in claiming a program is non-responsive while it's still actually working.

**Comment by tombula77** [comment] 2021-03-24 18:58
Max around 15 min i suppose.

**Comment by PocketfulOfGeese** [comment] 2021-03-24 19:00
I would recommend gathering a Sampler on it while it loads, through visualvm or the like, to see what it is actually hanging on doing.

**Comment by tombula77** [comment] 2021-03-25 09:41
OK here are some data from VisuaVM:

**Overview:**

PID: 8444
Host: localhost
Main class: net.minecraft.launchwrapper.Launch
Arguments: --username Tombula77 --version 1.12.2-forge-14.23.5.2854 --gameDir C:\Users\tombu\AppData\Roaming\.astraltest --assetsDir C:\Users\tombu\AppData\Roaming\.minecraft\assets --assetIndex 1.12 --uuid 52dd2e7f6d44444e81846b5ce68f8e5a --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjFjZmEyN2U1Y2M0NzAwOTYwZDc3MDUxYzUzNjBjYiIsInlnZ3QiOiI1MWY2YWQ2NjdiNDA0NmRkYmQ4NmQyMzNhM2EyMTRkZSIsInNwciI6IjUyZGQyZTdmNmQ0NDQ0NGU4MTg0NmI1Y2U2OGY4ZTVhIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTY4MzY4MDAsImlhdCI6MTYxNjY2NDAwMH0.KkOueDcH0YTdzodX0b_VIv0nE-qPJgGEqCPkg1Q_ppg --userType mojang --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge --width 1600 --height 900

JVM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09, mixed mode)
Java: version 1.8.0_281, vendor Oracle Corporation
Java Home: C:\Program Files\Java\jre1.8.0_281
JVM Flags: <none>

Heap dump on OOME: disabled

**JVM Arguments:**

-Dos.name=Windows 10
-Dos.version=10.0
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Djava.library.path=C:\Users\tombu\AppData\Roaming\.minecraft\bin\ac68-c4e5-6007-af7e
-Dminecraft.launcher.brand=minecraft-launcher
-Dminecraft.launcher.version=2.2.2311
-Dminecraft.client.jar=C:\Users\tombu\AppData\Roaming\.minecraft\versions\1.12.2-forge-14.23.5.2854\1.12.2-forge-14.23.5.2854.jar
-Xmx2G
-XX:+UnlockExperimentalVMOptions
-XX:+UseG1GC
-XX:G1NewSizePercent=20
-XX:G1ReservePercent=20
-XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=32M

**System Properties:**

awt.toolkit=sun.awt.windows.WToolkit
file.encoding=Cp1250
file.encoding.pkg=sun.io
file.separator=\
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2854\forge-1.12.2-14.23.5.2854.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-debug-all\5.2\asm-debug-all-5.2.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2_mc\scala-continuations-library_2.11-1.0.2_mc.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2_mc\scala-continuations-plugin_2.11.1-1.0.2_mc.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\tombu\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar;C:\Users\tombu\AppData\Roaming\.minecraft\versions\1.12.2-forge-14.23.5.2854\1.12.2-forge-14.23.5.2854.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_281\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre1.8.0_281\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre1.8.0_281
java.io.tmpdir=C:\Users\tombu\AppData\Local\Temp\
java.library.path=C:\Users\tombu\AppData\Roaming\.minecraft\bin\ac68-c4e5-6007-af7e
java.net.preferIPv4Stack=true
java.rmi.server.randomIDs=true
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_281-b09
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_281
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.281-b09
line.separator=\r\n
minecraft.client.jar=C:\Users\tombu\AppData\Roaming\.minecraft\versions\1.12.2-forge-14.23.5.2854\1.12.2-forge-14.23.5.2854.jar
minecraft.launcher.brand=minecraft-launcher
minecraft.launcher.version=2.2.2311
os.arch=amd64
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.boot.class.path=C:\Program Files\Java\jre1.8.0_281\lib\resources.jar;C:\Program Files\Java\jre1.8.0_281\lib\rt.jar;C:\Program Files\Java\jre1.8.0_281\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_281\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_281\lib\jce.jar;C:\Program Files\Java\jre1.8.0_281\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_281\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_281\classes
sun.boot.library.path=C:\Program Files\Java\jre1.8.0_281\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=net.minecraft.launchwrapper.Launch --username Tombula77 --version 1.12.2-forge-14.23.5.2854 --gameDir C:\Users\tombu\AppData\Roaming\.astraltest --assetsDir C:\Users\tombu\AppData\Roaming\.minecraft\assets --assetIndex 1.12 --uuid 52dd2e7f6d44444e81846b5ce68f8e5a --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MjFjZmEyN2U1Y2M0NzAwOTYwZDc3MDUxYzUzNjBjYiIsInlnZ3QiOiI1MWY2YWQ2NjdiNDA0NmRkYmQ4NmQyMzNhM2EyMTRkZSIsInNwciI6IjUyZGQyZTdmNmQ0NDQ0NGU4MTg0NmI1Y2U2OGY4ZTVhIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTY4MzY4MDAsImlhdCI6MTYxNjY2NDAwMH0.KkOueDcH0YTdzodX0b_VIv0nE-qPJgGEqCPkg1Q_ppg --userType mojang --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge --width 1600 --height 900
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1250
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=PL
user.dir=C:\Users\tombu\AppData\Roaming\.astraltest
user.home=C:\Users\tombu
user.language=pl
user.name=tombu
user.script=
user.timezone=Europe/Belgrade
user.variant=

**Here are screenshots from charts:**

https://i.ibb.co/frw4SvX/VVM-Monitor.png

https://i.ibb.co/KDfzK8w/VVM-Threads.png

In task manager minecraft are marked as not responding, cpu usage 0, memory usage increase 0,2M/refresh (normal speed).

**Comment by PocketfulOfGeese** [comment] 2021-03-25 10:05
Need the data off the Sampler tab.

**Comment by tombula77** [comment] 2021-03-25 10:18
There's a lot of data, which one ? 

CPU: CPU samples / thread CPU time / thread Dump
Memory: Heap histogram / per thread allocation / Heap Dump

**Comment by PocketfulOfGeese** [comment] 2021-03-25 10:23
Cpu.

**Comment by tombula77** [comment] 2021-03-25 10:32
https://i.ibb.co/x2gnSwX/CPUsamp1.png
https://i.ibb.co/Fzw0br8/CPUsamp2.png
https://i.ibb.co/XDtFZ3x/CPUsamp3.png
https://i.ibb.co/7tf9gTc/CPUsamp4.png
https://i.ibb.co/yhj7VnJ/CPUthre.png

https://pastebin.com/FzmXi5xd

**Comment by PocketfulOfGeese** [comment] 2021-06-23 15:55
```Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 984386536 bytes (938 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M```

Forgot to close this out previously, but this is reporting that the default java args are being used for older java and low memory allocation for original provided log issue.

**Closed as completed by PocketfulOfGeese** 2021-06-23 15:55 UTC
Labels: Resolution: Not my Mod/Won't Fix, Version: 1.15.2
