### ISSUE TITLE
Mantle of the Stars Vicio

### ISSUE THREAD

**Issue by NillerMedDild** [HellFirePvP/AstralSorcery#719] opened 2018-05-21 13:25 UTC
Same as #651 #312 #704, but on version 1.8.10 of AS.

The Elytra effect of the Mantle turns on for a split second, before cancelling. This is happening in Single Player, in the modpack Enigmatica 2: Expert. 

I have attempted to reproduce it with only AS and JEI, and I have not been able to. The modlist is pretty big, so I was hoping you guys could point me in the right direction.

I didn't spot anything in the latest.log, but here it is anyway:
https://gist.github.com/NillerMedDild/a501cac97c7a80c96bce09e71d520315

Modlist: 
https://gist.github.com/NillerMedDild/65ba42203e60a16d2cae2a819b5863d2

Forge 1.12.2-14.23.3.2689
Astral Sorcery 1.12.2-1.8.10

**Comment by Doomgull** [comment] 2018-05-21 19:51
Look into the Broken Wings config, make sure it's not killing elytra flight. Alternatively, remove only that mod and see if it replicates still

**Comment by NillerMedDild** [comment] 2018-05-22 08:35
Broken Wings is configured not to disable Elytra flight, in the problem persists with Broken Wings removed.

**Comment by HellFirePvP** [comment] 2018-05-26 23:28
Could you try binary search for the problem? So basically back up all your stuff somewhere safe, then remove roughly half of the mods and see if the issue persists (ofc with AS still added). If it does then split again. If it doesn't take the other half with AS and see if it persists there. If it doesn't, then merge both parts together as one pack again and try a different splitting. That way you can quickly narrow down which mods interacting causes this.

**Comment by NillerMedDild** [comment] 2018-05-27 07:32
Alright, I will, but not for a while, gotta get exams over with first :)

**Comment by winauer** [comment] 2018-05-27 17:20
It is caused by colytra. I have reported it here: TheIllusiveC4/Colytra#10

**Comment by HellFirePvP** [comment] 2018-05-27 20:17
Yep. their ASM patch is messing up the elytra handling. Them adjusting their patch solves this. As nothing needs to be done from my end, i'll close this.

**Closed by HellFirePvP** 2018-05-27 20:17 UTC
Labels: bug, mod interaction
