### ISSUE TITLE
Vicio Autostep Perk

### ISSUE THREAD

**Issue by Chibi-Zilla** [HellFirePvP/AstralSorcery#198] opened 2017-06-15 23:19 UTC
So I'm not sure _how_ this happens, but often with the autostep perk it won't limit me to stepping up a single block, and will instead jump me up to the top of ledges of any height (though if the jump is too far the server will usually rubber-band me right back to the ground for breaking the speed limit).
This will even jump gaps between blocks, occasionally leaving me on top of trees or similar should I step up a ledge underneath one.

**Comment by HellFirePvP** [comment] 2017-06-17 13:06
It's mainly because it's written in a way to scale with other auto-step things like sash from botania or whatever, so you can 'stack' it. That also can lead up to letting you step up 3-4 blocks.

Now was this with only AS alone or in combination with other mods' step assist things? If it happens with only AS, can you provide maybe steps to reproduce this?

**Comment by Chibi-Zilla** [comment] 2017-06-17 16:02
AS was the only step-assist active. I don't what triggers it, but it switches on or off at random if I die. I'll see if I can narrow anything down.

**Comment by HellFirePvP** [comment] 2017-06-17 16:12
Well, if you can find the steps to reproduce this, that'd be amazing

**Comment by HellFirePvP** [comment] 2017-07-02 07:48
Potentially fixed in the latest 1.12 version. Due to you and me not being able to consistently reproduce it, i call this solved.

**Closed by HellFirePvP** 2017-07-02 07:48 UTC
Labels: bug, Fixed/Added next update, needs more information
