### ISSUE TITLE
[Crash][1.16.4] Clicking starlight crafting altar entry in astral tome crashes to desktop.

### ISSUE THREAD

**Issue by Kinsypoo** [HellFirePvP/AstralSorcery#1781] opened 2021-03-30 06:38 UTC
[crash-2021-03-30_02.36.19-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6226753/crash-2021-03-30_02.36.19-client.txt)

**Comment by Jeuvke** [comment] 2021-03-30 12:39
Can't reproduce. Maybe try again without optifine, since optifine can cause weird issues sometimes. 
Also could you myabe write down more detailed steps to reproduce?

**Comment by Kinsypoo** [comment] 2021-03-30 21:01
Report from the person who found it: [crash-2021-03-29_23.29.19-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6232033/crash-2021-03-29_23.29.19-client.txt)


Report from someone without optifine: [crash-2021-03-30_15.55.20-client.txt](https://github.com/HellFirePvP/AstralSorcery/files/6232138/crash-2021-03-30_15.55.20-client.txt)


It's anytime we open certain entries of the astral tome. He discovered it also happens with astral relay's entry after i posted the issue. The steps we follow to reproduce it are just opening the astral tome, and clicking on the entry for that item to read it. It crashes us all to desktop with or without optifine every time we open the entry. 

I didn't change any of the configs for astral or anything either. Not sure why it's not happening for you. Maybe its a conflict with one of the other mods, but i dont know which one it could be if that is the case.

**Comment by Kinsypoo** [comment] 2021-03-30 21:12
Might be worth noting all the tabs with issues we have found so far seem to have some sort of multiblock instruction inside them.

**Comment by Jeuvke** [comment] 2021-03-31 20:45
This seems like a mod conflict. Could you try doing a binary search to see which mod(s) cause the conflict?

**Comment by Kinsypoo** [comment] 2021-03-31 21:00
i dont know how to do that.

**Comment by Jeuvke** [comment] 2021-04-01 00:14
Split your mod list in half, then check both halves (with astral sorcery and its dependencies) if the crash still happens. Then keep splitting the half it occurs in in half again and repeat. Make sure to keep dependencies together with their main mods though.

**Comment by Kinsypoo** [comment] 2021-04-02 21:59
sorry for the delayed response we discovered it seems to only happen in multiplayer not in singleplayer so i can't really find the mod conflict that way without shutting down the server to use it to test. Any suggestions?

**Comment by hron84** [comment] 2021-05-02 20:23
@Kinsypoo try to remove RandomPatches, it is mentioned in the crash itself, I think its mixin somehow clashes with AS.

Also, replace Optifine with Chlorine, it's less intrusive. As you have minig helmet, loosing dynamic lights is not a deal, for Zoom, you can use SimpleZoom. Shaders are the only thing you lose without Optifine, but most mod aren't compatible with shaders.

**Comment by HellFirePvP** [comment] 2021-06-01 18:22
Should be fixed with ObserverLib 1.5.3

**Closed as completed** 2021-06-01 18:23 UTC
Labels: Resolution: Fixed/Added next update, Type: Rendering Bug, Version: 1.16.X
