### ISSUE TITLE
falling star despawns before reaching ground

### ISSUE THREAD

**Issue by GeekBeam** [HellFirePvP/AstralSorcery#915] opened 2018-11-21 22:14 UTC
I'm not sure if this is due to me rushing up to meet it for a few moments, then plumetting back down, but I have seen several shooting stars that I have tried to track, but I look down to deal with some hostile mob, and look back up to find the shooting star is gone.

might be due to being despawned due to distance? not too sure...

**Comment by Doomgull** [comment] 2018-11-21 23:49
They don't last long once they hit ground, and they'll despawn if they travel into an unloaded chunk.

**Comment by HellFirePvP** [comment] 2018-11-25 11:32
Well yea. As it's been said, they despawn rather quickly. Closing this.

**Closed by HellFirePvP** 2018-11-25 11:32 UTC

**Comment by Banderi** [comment] 2020-04-19 14:24
How long exactly are we talking here?
I had one fall literally in front of me; I tossed some stone to free the inventory, and the Casing disappeared below my feet. Must have been at most 10 seconds. Does that sound correct, or is it a bug that makes it not able to be picked up in my pack?

**Comment by Doomgull** [comment] 2020-04-19 14:28
Sounds correct. Very short lived once hitting ground.

**Comment by Banderi** [comment] 2020-04-19 18:44
Oof, that's tough.
A friend told me it's an incredibly rare event too. That really blows.

**Comment by Doomgull** [comment] 2020-04-19 18:47
There's a decent chance per person, each night. Your friend is mistaken.

https://www.youtube.com/watch?v=BGUK0SC3pbE

**Comment by Banderi** [comment] 2020-04-19 19:30
Could you define "decent" please? The video is kinda confusing and vague. It does mention that they are generally extremely far away and I've chased a few myself confirming this - my friend has only been able to fetch one out of more than 200 hours played in various modpacks with Astral Sorcery. Many threads also report they are incredibly hard to get before they despawn. So yeah, I'd say the chance of having one drop right on your feet is incredibly rare.

**Comment by Doomgull** [comment] 2020-04-19 19:31
They don't drop at your feet. They travel, as explained. This conversation is more of a thing for the Discord, not a bug ticket.
