### ISSUE TITLE
Animation/Sound Glitch

### ISSUE THREAD

**Issue by KyBeeS** [HellFirePvP/AstralSorcery#1829] opened 2021-06-09 01:20 UTC
When crafting any recipe in Astral the altar keeps doing the sounds and animations after the craft has already finished. Issue present in atm6 and atm6 sky from multiple player sources.

**Comment by Jeuvke** [comment] 2021-06-09 21:09
Duplicate of #1816. Upgrade to Astral Sorcery 1.13.12.

**Closed as completed** 2021-06-22 15:13 UTC
Labels: Resolution: duplicate
