### ISSUE TITLE
Compat issue with Blockbuster

### ISSUE THREAD

**Issue by Tschipp** [HellFirePvP/AstralSorcery#1018] opened 2019-03-01 13:52 UTC
When recording an action with blockbuster and then replaying that action using the command "/action play <recordingName>", the command is not executed and an error is thrown:

https://pastebin.com/VrDMR4cz

Removing Astral Sorcery fixes the issue.
I'm using AS 1.10.11 and Forge 14.23.5.2811

**Comment by Doomgull** [comment] 2019-03-01 14:52
Already fixed in-dev by forcibly nulling out the wrong player class call in other mods when it comes up, wait for 1.10.12.

The issue is that blockbuster is calling the improper player class, by the forge documentation.

**Closed** 2019-03-01 14:52 UTC
Labels: Fixed/Added next update, bug
