### ISSUE TITLE
Illumination wand strange functionality at some chunk boundaries.

### ISSUE THREAD

**Issue by VallenFrostweaver** [HellFirePvP/AstralSorcery#1509] opened 2020-12-02 12:40 UTC
MC: 1.16.4
AS: 1.13.1
Observlib: 1.4.4
Curios: 4.0.3.0
Clicking an illumination wand light on or off has strange functionality and the light starts/stops inconsistently at chunk edges. I sent a video to @HellFirePvP via Discord.

**Comment by HellFirePvP** [comment] 2020-12-06 13:52
Since i cannot reproduce the described behavior and i'm not really tampering with any part of lighting updates directly, i'm beginning to doubt i'm responsible for this or have a large ability to fix this...
Closing it for now.

**Closed by HellFirePvP** 2020-12-06 13:52 UTC
Labels: Note: uncertain fixability, Type: Bug, Version: 1.16.4
