### ISSUE TITLE
[1.13.9] Merging Crystals rarely absorbs block next to starlight.

### ISSUE THREAD

**Issue by telemenar** [HellFirePvP/AstralSorcery#1780] opened 2021-03-28 20:47 UTC
Occasionally when merging two crystals in a 1 bucket hole, they absorb the block next to the starlight rather than the starlight.

**Comment by BlueAgent** [comment] 2021-03-29 01:10
Duplicate of https://github.com/HellFirePvP/AstralSorcery/issues/1618 perhaps?

**Closed as completed** 2021-05-27 08:16 UTC
Labels: Type: Bug, Resolution: duplicate
