### ISSUE TITLE
Just feedback..

### ISSUE THREAD

**Issue by kbcoder** [HellFirePvP/AstralSorcery#235] opened 2017-07-13 00:24 UTC
Been really wanting to go through this mod, but currently there are issues that makes it more aggravating then enjoyable.  Here are some key things which you may want to consider or note.

1) Most of the youtube videos, even the latest ones out there are either too vague, processes have changed, names of items have changed, etc.. to the point that it gets you somewhat in the right direction, but confuses you for the most part.  This could be corrected with easier explanations in the book keeping things up-to-date. The book itself, I do like how it progresses, but the text is what needs to be worked on, seems to be way too much in how things are formed, then what practical uses it is intended for when it comes to using it. I find myself thinking 'ok, that's all cool, but what the  hell is it used for?'.. then going to youtube videos to be more confused because so many things have changed.

2. The constellation papers process needs to be re-thought. I have 48 in my inventory (survival mode) and all say 'There is Nothing here'. Yet, in the book on the constellations tab I have 4 appearing there. By watching videos they have constellation papers with names on them and they can hold them in the off hand and place 'relays' where indicated on the attunement alter. Well, I don't have a single paper with a name on it and holding the book in my off-hand does nothing, so I'm left with no way to know how to place the relays I guess. There should be an alternative method for this and if there is, then better explanation. This pretty much stops all progress in the attunement category for me which I am thinking is the most. 

Please note, I love the mod and can't wait for it to get to a point where it is less confusing to work with. Big thanks to all the hard work which has been fed into the mod and I definitely want to keep up-to-date with the progress so hopefully I can get further into the mod at some point. 

Thanks

**Comment by DrDelius** [comment] 2017-07-13 06:07
Just to second this, I've only found 4 papers on a (ATM2) server that don't say 'There is Nothing here', after about 100 hours of playing and raiding every structure I can find. You need a way to "discover" new constellations with the blank paper, because it is completely useless. Everyone on the server seems to be having the same problem, so very few of us are even attempting AS progression. 

Don't get me wrong, this might be my favorite new mod, but there are definitely some issues to work out. 


Also, the scroll-in scroll-out mechanic is infuriatingly slow. Give an options menu, or allow double clicking or something.

**Comment by Doomgull** [comment] 2017-07-13 10:35
Some of the mechanics have changed since those people did those videos. That said the attunement papers system did go through an alteration since the earlier videos were done, and what your seeing sounds like it could be a progression issue.

What version are you running, I'll run some tests when I get back home unless it's a known issue in your version, assuming HellFire doesn't get to this first and provide corrected information.

**Comment by kbcoder** [comment] 2017-07-13 18:41
Hey Doomgull, we are using 1.4.5 for mc 1.11.2.

At least while I am at it and it seems like you guys are willing to listen instead of taking things as stark critism, I'll add a few more suggestions which you can take for whatever it is worth.

Would be nice to have more unique usable items that can be crafted through the different tears of the crafting stage progression. It felt that I was upgrading crafting tables in order to be able to upgrade it again.  Having more unique items that can be built through each stage would do a lot.  At starlight crafting alter (Discovery) you get to make 'crystal tools' via the now craft-able grindstone. After working with it for about an hour, I found that it got tedious quickly and in order to get anything close to what other mods provided much easier, it would be a 'grind' ..no pun intended.  I left it with, 'let me progress further in the mod and at some point I will spend the time to see how well I can max out a crystal tool'. 

After spending several hours with it, this is what I have gotten out of the mod.
1) A time consuming way of making really good 'tools' and the ability to sharpen weapons from other mods.
2) A light source that lights up caves very NICELY and with a huge range. (probably my fav thing so far)
3) A wand to turn things transparent and indestructible.
4) Ways to transmute some blocks into another type of block (btw - the pumpkin to cake would have been really useful (in my mod situation) if you could pick up the cake. lol)

tbh, that's about it.. I'm stuck not being able to progress in attunement and I'm guessing and hoping that is where the heart of the mod lies.

**Comment by DrDelius** [comment] 2017-07-13 20:38
ATM2 .72d, it has Astral Sorcery 1.4.4

I'm having two separate issues: 

1) I only ever found 4 constellation papers that had constellations on them, all the others are blank. Is this a new progression system? I didn't see it in the book, but I could have missed it. I found 2 of the 4 in the sky with the telescope, but can't seem to get my attunement setup to have the glowing lights that show me where to place the things so I can't get attuned. I'm trying without having the paper directly in my hand, obviously, is that what's wrong? or is it the "progression" stuff you mentioned, I need to unlock something else?

2) I had a corrupted chunk because of a different mod, but I lost my book with all four of my papers. I can't get those papers back any way and can't get new ones cause all the paper is blank since I found the originals (and I know of someone who had their chests raided that lost theirs). You need to make a mechanic that will allow us to change "blank" constellation paper into none blank ones, it's killing my server attempt at A.S.


I like the flow, don't mind having to work a bit on a new mod, but progression needs to be more clear and the book more easily usable.

**Comment by HellFirePvP** [comment] 2017-07-14 12:20
Alright, that's a wall of text, i'll go through it one by one i suppose?

1. Youtube videos being outdated: I don't make them, neither am i responsible for keeping the mod the same way forever when a video is made. Mods change and add things. Not my fault or responsibility.

2. The way that constellation papers work: If you haven't 'memorized' or 'discovered' a constellation, but you could unlock it, then a constellation paper assigns itself to a constellation and that one becomes 'memorized'. A 'blank' constellation paper will stay blank if there's no unknown constellation or no constellation is unlockable at the moment. "There is Nothing here" = blank. They're not "worthless" they just can't assign themselves to a new one. The root of this problem and why i now chose to implement them this way lies deeper. The previous solution was that i would scan the player's inventory (and items containing inventories) for other constellation papers and collect the constellations that the player has found that way. If one was missing, assign the currently searching blank one to that constellation. The complained-about result: 50 constellation papers all assigned to the 4 "bright" ones and no blank ones leftover for the "dim" ones once the progress for them got reached. The current approach that at least counters inventory-spam is the one you know and hate now. Also not great, but it should encourage leaving blank constellation papers behind for players that don't have all of them memorized yet. Or so i thought. Apparently people like hoarding just for the sake of hoarding items that are not useful to them anyway... The original problem where this all originates from: It is impossible to track itemstacks. I have no idea if you're carrying around your constellation papers, if you have them in a ME system, in some chests, storage drawers, ... - Thus in the 1st approach explained i can't detect what constellation papers you already have unless you have them all with you, or if not you end up with hundreds of duplicates. The 2nd approach makes losing one extremely punishing, which is - true - also not intended. However, i also don't want to "randomly assign to a constellation" - because then you need potentially a huge amount of them to get all 10 currently available constellations because of "bad luck". If you know a "better" approach that doesn't include adding random-ass crafting recipes for every paper "because reasons", then please do suggest that.

3. The attunement & player attunement with perks, but specifically crystal attunement & the ritual-AOE effects cast by the ritual pedestal for specific constellations is the main content-part more or less at the moment. The mod has less content than you might think imo. kinda. idk. people tell me it has a lot of content... so. *shrug*

4. the tree beacon crashing there would then indeed be a bug that didn't get reported yet, thanks for reporting that one then.

5. @ DrDelius yes, you need to progress and do 'a certain thing' then you "unlock" the next 6 constellations.

6. Same as 2. in here.

**Comment by kbcoder** [comment] 2017-07-14 17:53
Thanks HellFire for the response. As far as #1 goes, I want to make it clear that I wasn't blaming you of course for the youtube videos, my post was to explain the difficulty of progression do to the combination of 'that' fact and that the ingame book itself is very vague (which from what I gather by some of your previous responses), is intentional.  I really would like to help in any way I can, but I also don't want to risk pissing you off or discouraging you. 

If I'm understanding you correctly, the goal of the constellation papers is to force players to go out and explore the world and collect constellations (memorizing them). This wouldn't be a problem if you didn't have to have a physical 'named' constellation paper in hand to progress in attunement.  I have no clue of the capabilities of minecraft moding, but let me throw some things at you and see if anything is worthy of sticking.

1. How about using the achievement system as a means to track if a player has 'memorized' a constellation or not and whenever a player opens the astral sorcery book (journal), you check those achievements and then on the constellations tab you only show the ones that person has memorized. Clicking on the constellation will bring open it up as it is, but add an additional 17x17 attunement grid (sooty part) representing how one would have to align the relays up to progress in attunement.

If a person could do this, you then don't have to worry about keeping track of the constellation papers or inventory systems.  Constellation papers could be randomized in the world based on 'rarity' and then the player (when finding it) just holds it in hand and right clicks it in the air to get the  achievement (paper disappears). If the player already has the achievement, just send a chat message that says 'you have already memorized this constellation, please leave paper for another wandering adventurer. You won't even have to have blank constellation papers with this, just have the papers static, but spawned based on a rarity value.

Just some ideas..not sure if anything will help or not, but I'm trying.

**Comment by DrDelius** [comment] 2017-07-15 02:23
Suggestion for constellation papers as they already are: allow named ones to be copied so that I can make copies for my friends or an extra for myself or copies from when I lose mine. I know it counts as a BS crafting thing. My other idea is to add an X to the constellation in the book to unlearn it, so we can relearn it from a blank paper.

**Comment by HellFirePvP** [comment] 2017-07-15 12:44
I tried reproducing the tree-beacon issue without success. Might be some other mod interfering with this?

I have an idea how i'm gonna adress the constellation paper problem, however other things will take priority before that unfortunately.

**Comment by kbcoder** [comment] 2017-07-15 21:24
I'll try and do some more testing HellFirePvP on that one to see if it is still doing it. It very well could be another mod interfering with something. Basically,I would just put down the tree-beacon, plant some trees around it and then start clicking bonemeal on the tree and after a few seconds the server CPU would cap out and disconnect the clients.  The tree never grew btw so that is why I thought it might have  something to do with the growth timing or something.

**Comment by Doomgull** [comment] 2017-07-15 22:08
Is it possible to have profiling running when it caps to try to see what specifically is capping it like that? I would imagine it's some sort of loop, but...

**Comment by Doragoon01** [comment] 2017-08-10 01:46
How about if the journal's inventory was an ender inventory type system where it was linked to the player, not the book?  That way you put the paper in and you always have it.  Even if you loose the book, when you got a new one, it would have all your old papers in it.  and if someone else picked up your book, it would only have the papers that they themselves discovered.

Also, the papers say to leave them in the chest if they are blank so someone else can use them.  should i have actually been picking those up so that i can use them to get the minor constellations?  If you need them later, don't tell people not to pick them up.

I've spent the past week (real time) trying to brute force my way through all the hundreds of different line combinations to get the minor constellations.  I finally gave up and found the section of code that defines them, and wrote an excel sheet to plot them.  (This took less time than i'd already spent accomplishing nothing.)  Turns out it wasn't that i was drawing them incorrectly, it's that i needed all those papers that i'd thrown away.

The discovering things for yourself and the immersion of the journal can be nice, but it feels like there would be a lot less frustration all around if you included a few more specifics to guide people in the right direction.  As is, it's impossible to tell if something isn't working because you did something wrong while understanding it correctly, or you misunderstood the instructions, or the functionality has changed since the journal text (or youtube video) was written, or if it's a legitimate bug.

Finally, the tools are nice, but like kbcoder said, there are better options.  I have no clue why i'd ever go through the effort of making them rather than set up an AFK fishing farm to get books and experience with which to make a diamond pick with efficiency 5 and mending.  It would certainly take me less time.

**Comment by Doomgull** [comment] 2017-11-01 12:39
Going to close this. All points in here are either addressed , involve a now-unsupported version of the mod without recurrence reported in an MC 1.12.x or later version, or involve the lost constellation papers thing (which has a way to manually recreate the constellation papers).

**Closed by Doomgull** 2017-11-01 12:39 UTC
Labels: design issue, question, suggestion
