### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by Dryelo** [HellFirePvP/AstralSorcery#1837] opened 2021-06-19 10:33 UTC
hello there,

I had two server crashes while fighting an armored zombie from Dungeons Mobs.

The dev there told me to let you know... so here I am :)

[crash-2021-06-16_18.44.26-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/6680506/crash-2021-06-16_18.44.26-server.txt)

edit: link to my original post
https://github.com/Thelnfamous1/Dungeons-Mobs/issues/26

**Comment by Jeuvke** [comment] 2021-06-21 21:53
This does not appear to be caused by AS. The tetra dev in your other post said it was fixed in their latest release, so I think it was their issue instead.

**Comment by PocketfulOfGeese** [comment] 2021-06-22 14:27
https://github.com/mickelus/tetra/issues/451

**Closed as completed by PocketfulOfGeese** 2021-06-22 14:27 UTC
Labels: Resolution: Not my Mod/Won't Fix, Version: 1.16.X
