### ISSUE TITLE
Crash on world generation

### ISSUE THREAD

**Issue by Darkmega18** [HellFirePvP/AstralSorcery#400] opened 2017-11-30 18:53 UTC
[crash-2017-12-01_05.40.03-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1519090/crash-2017-12-01_05.40.03-server.txt)

got this for you. crashed upon world generation. something about a fluid rarity register and "hascapability"

edit: I may need to say that I'm using the last version that you have that's still meant to work for 1.12.1. Due to modpack making reasons (lack of everything updated). so I have a bad feeling I probably won't get this update even if you do fix. :<

**Comment by crimso** [comment] 2017-12-01 07:55
Hello 

I have the same problem, I am using Direwolf 20s 1.12 pack, crash log below

[crash-2017-12-01_05.31.20-server.txt](https://github.com/HellFirePvP/AstralSorcery/files/1520788/crash-2017-12-01_05.31.20-server.txt)


Thank you

**Comment by TimGoll** [comment] 2017-12-01 12:38
my game crashes on worldGen too. But another log. Here it is: [crashReport](https://gist.github.com/TimGoll/e11306095c295ab8f81e7a29a7ab86e5)

**Comment by TimGoll** [comment] 2017-12-01 21:09
Had some forge problems today with 5557, downgraded to 5555. Wait a moment, I'll test it with this version

**Comment by TimGoll** [comment] 2017-12-01 21:15
crash occurs with 5555 too

**Comment by Darkmega18** [comment] 2017-12-02 04:49
previous version 1.7.3 works fine. although I've yet to start using the mod due to modpack "production" reasons. I have the forge which is currently the latest foe 1.12.1:  forge 1.12.1 - 14.22.1.2485

**Comment by HellFirePvP** [comment] 2017-12-03 15:07
On Thut's end.

**Comment by HellFirePvP** [comment] 2017-12-03 19:01
Has been fixed on Thut's end & is awaiting release. https://github.com/Thutmose/Thut/issues/78

**Comment by Darkmega18** [comment] 2017-12-04 09:50
You ready for this? ... I don't have any thut stuff installed. *shrugs* atleast nothing that is blatantly named thut. or anything that had required it. and my crash log was the original here. so.... what do?

**Comment by HellFirePvP** [comment] 2017-12-04 19:43
Yea. in your case, you're using a outdated forge version and don't have the bug others reported on this issue.

**Comment by Darkmega18** [comment] 2017-12-05 01:36
so the 1.8.0 doesn't work with 1.12.1 after-all and it's a mislabel? since I took the latest forge that works for 1.12.1 which is 14.22.1.2485. :V

**Comment by HellFirePvP** [comment] 2017-12-05 17:13
1.12.1 is no longer supported since this yea.
and the issue is (or is being) resolved on thut's end.

So. yea. closing this.

**Closed by HellFirePvP** 2017-12-05 17:13 UTC
Labels: bug, mod interaction, Not my mod
