### ISSUE TITLE
Game is soft-killed when traveling to certain location

### ISSUE THREAD

**Issue by Hiranus** [HellFirePvP/AstralSorcery#1452] opened 2020-11-14 10:25 UTC
**Observed Behaviour**
When checking my currently generated world I found area that "soft kills" MC. I can still move around, but I can't attack any mob, can't receive any damage, no chunks will be generated or loaded. When I try to break block nothing is dropped, and snow as well as grass are just "floating". Similar with gravel and TNT. See attached pictures.
If I try to save and quit game is stuck in never ending "Saving world".
If I remove any of the mods mentioned below area that cause this issue works normally, but its impossible to confirm that it is fixed, as I suspect that generation slightly changes and problematic "something" is moved to different location.

Crash log: 
https://pastebin.com/Fdca0kZ4
https://pastebin.com/HUCYnFnK
One of the mods mentions minecraft:bigdungeon, but i couldn't find it in sources of mentioned mods.
I know that there is no clear "error". Nothing else is generated in log.

**Expected Behaviour**
Problematic area works normally. I expect its issue with some dungeon generated by this mod/this combination of mods.

**Minimal setup needed to reproduce**
- Forge version: 1.15.2 - 31.2.46
- Mod configuration: default, I didn't change anything.
- Mods required to reproduce: 
astralsorcery-1.15.2-1.12.11
BiomesOPlenty-1.15.2-10.0.0.366-universal
curios-FORGE-1.15.2-2.0.2.6
DungeonCrawl-1.15.2-2.2.1
mgui-1.15.2-2.1.1
observerlib-1.15.2-1.3.1
tetra-1.15.2-2.18.1

**Steps to reproduce**
seed: 157733132531422357
X: 400
Y: 120
Z: 800

Create world with those mods, seed and travel to specified coordinates. I just do /tp 200 120 600 and fly there.

![image](https://user-images.githubusercontent.com/6943031/99130077-a5070e00-260f-11eb-8cf6-1899f48c8d03.png)
![2020-11-14_10 56 46](https://user-images.githubusercontent.com/6943031/99145003-2f309000-266b-11eb-9c34-ce31a3818316.png)

**Comment by Hiranus** [comment] 2020-11-14 10:27
I couldn't reproduce it without DungeonCrawl and Tetra so I created bug reports there too.
https://github.com/mickelus/tetra/issues/239
https://github.com/XYROC/DungeonCrawl/issues/51

**Comment by HellFirePvP** [comment] 2020-11-14 15:20
Uncertain what exactly this is..
The behavior you described would suggest a heavy lag or probably a infinite loop on the server thread. Thus the client still runs fine while the server is endlessly busy.

**Comment by Hiranus** [comment] 2020-11-14 15:24
@HellFirePvP Yeah. It also seems to happen when new chunks are generated. I managed to get it with way more mods in different location when I explored. If you want me to check something, see it for yourself etc I can easily reproduce it.

**Comment by HellFirePvP** [comment] 2020-11-14 15:37
I'm not sure i can do a whole lot about it? i'll take a peek when i get the time.

**Comment by Doomgull** [comment] 2020-11-14 15:50
Can you pastebin the serverlog from this occurring?

**Comment by Hiranus** [comment] 2020-11-14 15:51
@Doomgull  Everything I provided till now was in singleplayer. I'm just preparing to put stuff on the server.

**Comment by HellFirePvP** [comment] 2020-11-21 16:55
I did not have great success trying to reproduce this..
Same mod set and as you can see, same hillside.

![image](https://user-images.githubusercontent.com/7419378/99882696-b27d5300-2c22-11eb-9107-8ed5979af997.png)

**Comment by Hiranus** [comment] 2020-11-22 10:42
I dont even know what to say. I will switch Tetra to Silent Gear, start my server and hope that me and my friends wont ever find this bug again. I think you can close this.

**Comment by HellFirePvP** [comment] 2020-12-07 20:50
Since noone else has added onto this or idk what to do about this, i'll close this for now.

**Closed by HellFirePvP** 2020-12-07 20:50 UTC
Labels: Note: uncertain fixability, Type: Bug, Version: 1.15.2
