### ISSUE TITLE
Altars do not recognize vis crystals from thaumcraft correctly

### ISSUE THREAD

**Issue by TheBlackLuigi** [HellFirePvP/AstralSorcery#1030] opened 2019-03-12 21:26 UTC
Hello,
I changed the recipes for the seeds from mystical agriculture in a way that you need to use the different altars. Also, some vis crystals are required to complete the craft. The problem is that even though I referred to a crystal like that: <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "ignis"}]})
all vis crystals and not just the ignis one are allowed in the final recipe.

Version of AS: 1.12.2-1.10.11
zen-script: https://pastebin.com/7cMuizES

Look near the bottom to find the right recipes.

Thanks in advance,
Blackluigi

**Comment by HellFirePvP** [comment] 2019-03-26 20:05
Having trouble reproducing that.
https://i.imgur.com/mpO8L4a.png

**Comment by TheBlackLuigi** [comment] 2019-03-28 15:09
Yeah, that will work.
The recipe is specified that only ignis crystals are allowed in there. My problem is that other crystals can also be used. Try other ones such as terra or so. I'm trying to figure out whether another mod is causing this error. I have 140 installed so that takes a while xD. But thanks anyway.

**Comment by HellFirePvP** [comment] 2019-03-28 18:08
Oh, i will investigate that...

**Comment by TheBlackLuigi** [comment] 2019-03-29 09:12
Thanks man.
Also I tested whether another mod causes that but no. Can reproduce it with only A.S. and T.C.

**Comment by HellFirePvP** [comment] 2019-03-29 11:42
Because it's due to the way AS compares items.
Changed with https://github.com/HellFirePvP/AstralSorcery/commit/eec26378a219a3d5702eb9556e5c770bbc0758c2 and will be able to handle that kinda stuff with the next update.

**Comment by HellFirePvP** [comment] 2019-03-29 11:45
Should you wish to test it right now, you can grab the latest build(s) from maven: [https://maven.hellfiredev.net/hellfirepvp/astralsorcery/astralsorcery](https://maven.hellfiredev.net/hellfirepvp/astralsorcery/astralsorcery) - the build in question would be v91 or newer.

**Comment by TheBlackLuigi** [comment] 2019-03-29 20:00
Thank you very much for your support :D
It works fine with the -v92 version. I can now resume the development of my modpack.
Thanks again.
Blackluigi

**Comment by HellFirePvP** [comment] 2019-03-29 22:36
I will keep this open in case others have a similiar issue.
I'll close it once the next version releases.

**Closed** 2019-04-10 22:32 UTC
Labels: Fixed/Added next update, bug
