### ISSUE TITLE
Aevitas reach increase perk does not go away after Shifting Star usage [DW20 1.12 1.1.0]

### ISSUE THREAD

**Issue by welch3694** [HellFirePvP/AstralSorcery#404] opened 2017-12-01 15:58 UTC
Selected Aevitas perk for increased reach, reach now extends to 40 meters. Shifting Star does not reset mining reach to normal.

40 meters is too much (I had expected 8-10 maybe?), but when trying to clear it with the shifting star the reach remains the same. I've removed all my equipment and it is still there, I am unaware of any other mod that affects mining reach. I've attuned to Vicio instead of Aevitas just in case that might force it to refresh or something -- no effect. 

Screenshots below show increased mining reach, map marker I began at is 40m away, and shows my attunement is no longer to Aevitas so it should go away. Thanks!

![image](https://user-images.githubusercontent.com/1097586/33490838-5ecfb756-d686-11e7-8679-8cfa9bb356f0.png)

![image](https://user-images.githubusercontent.com/1097586/33490869-7547b52e-d686-11e7-8a33-0db75045cab7.png)

**Comment by welch3694** [comment] 2017-12-02 15:31
After a restart of both the server and the client, it seems to have gone away. I had only restarted my client previously.

**Comment by HellFirePvP** [comment] 2017-12-03 14:37
I am uncertain (so i leave this issue open for now) however i included a potential fix for this in 1.8.3 - uncertain if it will work as expected as i am unable to reproduce this issue however i do have an idea about where it might originate from. So once 1.8.3 is released, i'd like to ask you to try and reproduce the issue and then tell me if it got fixed with that or not.... :|

**Comment by HellFirePvP** [comment] 2017-12-09 15:57
Any update on this in 1.8.3?

**Comment by Grevas13** [comment] 2017-12-10 17:45
I am playing on v1.8.3, in the ATM3 pack.  Experiencing this same issue, after having used the Shifting Star and being retuned to Evorsio.

**Comment by Grevas13** [comment] 2017-12-13 01:31
Just checked with most recent forge version and 1.8.4 of Astral Sorcerery.  Reach increase no longer persists after using the shifting star.

**Closed** 2017-12-13 08:48 UTC
Labels: bug, Fixed/Added next update
