### ISSUE TITLE
Interaction with Botania Mana Spreaders and Armara Ritual

### ISSUE THREAD

**Issue by TheVekter** [HellFirePvP/AstralSorcery#1253] opened 2020-03-25 18:16 UTC
### Reproduction
1) Power or anchor an Armara ritual
2) Place down mana generation set-up (It doesn't matter how you generate it as long as causes the mana spreader to fire)
3) Link spreader to pool
4) Create mana

Expected: Mana reaches pool without issues
Actual: Mana burst is treated as a projectile (or mob???) and pushed away from mana pool

I'm not really sure if anything _can_ be done to fix this, given how mana bursts are coded, but it'd be nice to be able to run my favorite ritual without it breaking all my Botania stuff.

**Comment by Doomgull** [comment] 2020-03-25 18:18
Not a bug. Also not something to be addressed by AS, but Botania, see below.

Also #1195

**Closed by Doomgull** 2020-03-25 18:18 UTC
Labels: duplicate

**Comment by TheVekter** [comment] 2020-03-25 18:47
Laaaaame. I'll go yell at Vazkii, maybe he can fix it. Thanks anyway.
