### ISSUE TITLE
[1.12.2] Items cannot be removed from grindstone while holding offhand items

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [HellFirePvP/AstralSorcery#471] opened 2017-12-28 18:29 UTC
Minecraft 1.12.2 | Astral Sorcery 1.8.4 | Forge Server and Client 1.12.2-14.23.1.2560

When using the grindstone to grind starmetal ore and holding an object in your off hand, the stardust remains stuck in the grindstone and cannot be removed unless the grindstone is broken, at which point the stardust drops as well. Other ores ground into dust (grit from Immersive Engineering in this case) can still be removed from the grindstone normally with sneak+right click while holding items in the off hand.

https://imgur.com/a/NMJU0 Video demonstration

**Comment by Doomgull** [comment] 2017-12-28 18:31
Empty tue torches from off-hand.

**Comment by Doomgull** [comment] 2018-01-02 19:49
Problem with this has to do with shift+right clicking overriding the block's stuff, may not be able to do much about this.

**Comment by thedarkfalcon** [comment] 2018-01-20 04:20
Thanks for logging this bug, I couldn't figure out why it wasn't working and had to break the grindstone every time I wanted something out of it.

It could be fixed by making removing item a custom key like other mods have?

**Comment by HellFirePvP** [comment] 2018-01-20 10:05
No. the problem is that the shift-r-click doesn't get passed onto the block to do its logic if you have a item in your offhand but nothing in your mainhand. the block just never gets notified that anything happened. did it with a workaround now so.... it'll work at least.

**Closed** 2018-01-24 07:12 UTC
Labels: Fixed/Added next update, complex issue, minor
