### ISSUE TITLE
[1.16.4] Dupe issue

### ISSUE THREAD

**Issue by SeroMaster** [HellFirePvP/AstralSorcery#1884] opened 2021-08-26 00:04 UTC
Valhelsia 3.

Perk for transfering items in inventory combined with enchantment which does the same allows duping blocks. (Vicio path perk "Spatial Manipulation" + Charm's "Acquisition" enchantment"

**Comment by SeroMaster** [comment] 2021-08-27 16:57
Update

Problem weren't in double enchantments, but cause of Scarf of luck item from "Artifacts" modification. There's no dupe when use this scarf with enchanted pickaxe, so I guess issue is in Astral Sorcery.

**Comment by luna6667** [comment] 2021-09-20 00:46
What version of the mod are you on? This might be a duplicate of #1616

**Comment by PocketfulOfGeese** [comment] 2021-09-20 01:40
I can't replicate this under the latest version of Valhesia 3. I'm pretty sure this is the same already fixed issue.

**Closed as completed** 2021-12-01 23:55 UTC
Labels: Resolution: duplicate, Resolution: already fixed/update mod version, Version: 1.16.X
