### ISSUE TITLE
Mouse cursor disappears

### ISSUE THREAD

**Issue by MasterFee** [HellFirePvP/AstralSorcery#12] opened 2017-02-15 16:56 UTC
The mouse cursor disappears when I use the Hand Telescope and closing out of it using the Inventory button (Default: E). I'm using just basic mods like JEI, The One Probe etc. and running the pack using a Mac (might be the reason).

**Comment by MasterFee** [comment] 2017-02-15 16:57
And what am I doing wrong here?
![bildschirmfoto 2017-02-15 um 17 56 29](https://cloud.githubusercontent.com/assets/8414127/22985222/1d48686c-f3a8-11e6-8bb7-aa10db12f1ec.png)

**Comment by HellFirePvP** [comment] 2017-02-15 17:32
This bug has been reported by one of my alpha testers aswell, however he didn't have a lead on reproducing it realiably.. Your description might make more sense, i'll see if i can find the issue.

**Comment by HellFirePvP** [comment] 2017-02-18 11:46
@MasterFee does this persist in 1.1.2 ?

**Comment by MasterFee** [comment] 2017-02-18 11:49
Didn't try it yet. Going to try it today or tomorrow.

**Comment by HellFirePvP** [comment] 2017-02-18 11:57
Thanks

**Comment by MasterFee** [comment] 2017-02-18 12:02
Bug still persist in 1.1.2. Every time I use the Hand Telescope and press "E" to close the window the mouse cursor disappears. It will only come back if click outside Minecraft. Closing the GUI by pressing right click again seems not to cause the issue.

**Comment by HellFirePvP** [comment] 2017-02-18 12:04
So this issue only happens when closing it by pressing your inventory-key?.. opening another gui and closing said other gui does not make the mouse curor appear again?

**Comment by MasterFee** [comment] 2017-02-18 12:35
Yes, just like you said. But it happens after the attunement too. Opening other GUIs beside the ones I mentioned doesn't cause any problems.

**Comment by HellFirePvP** [comment] 2017-02-18 12:54
Alright, this seems OS specific, so it'll be a bit of a pain to debug properly, but i'll see what i can do about that in the next version.

**Comment by MasterFee** [comment] 2017-02-18 16:37
If I can assist you in any shape or form just let me know and I can see what I can do

**Comment by HellFirePvP** [comment] 2017-02-19 15:25
There's a chance that this might now be fixxed in 1.1.3, but well... we'll see, i guess >_>

**Comment by Febilian** [comment] 2017-02-19 20:15
I'm on OS X and using version 1.1.3, now I can't move the telescope window/my viewpoint around at all after right clicking with the hand telescope, and what's more, while the telescope is active/the star screen is open, even if I tab out, my cursor completely locks up and doesn't move until I exit out of the telescope's interface. It's really quite odd, and didn't happen before. I'm assuming that this is a result of whatever fix you tried for this issue here.

Also, the cursor is still gone when I'm using the telescope, but at least previously it kind of worked if I moved my cursor out of the window and back into Minecraft, so I could see where my cursor was when I would hold shift to draw on constellations. I can still do that as long as I'm holding shift when I move the cursor out of Minecraft's window and back, but otherwise it's just... stuck.

**Comment by MasterFee** [comment] 2017-02-19 21:29
So I can confirm what @Febilian said in the previous post. Star screen will open but won't move. Closing it only works by pressing 'E' - right clicking doesn't work at all. Cursor still disappears but I'm able to recover it if I tab out of Minecraft (using fullscreen mode, did not test windowed).
BTW using the standing telescope worked fine in the previous version, also did not not test in 1.1.3.

**Comment by HellFirePvP** [comment] 2017-02-19 23:28
Ugh.. so i guess that didn't work at all.. _fun_...

**Comment by MasterFee** [comment] 2017-02-28 10:28
Tested in new version (1.1.4) and still doesn't work. Seems to be the same as in 1.1.2... Right clicking works again and the GUI moves as intended but cursor still disappears if I right click OR press 'E'

**Comment by HellFirePvP** [comment] 2017-02-28 12:26
_Duh..._ That's awkward... -_- thought i fixxed that at least this time, but uh...

**Comment by HellFirePvP** [comment] 2017-03-08 16:14
_The usual question_

Did it work now in 1.1.5? >_>

**Comment by MasterFee** [comment] 2017-03-09 22:05
I'm afraid to tell you but it still does not work :/ GUI moves as intended but cursor disappears if I close the window either by right clicking or by pressing the inventory key. (Tested in 1.1.5)

**Comment by AntonTrapp** [comment] 2017-07-10 09:49
Astral Sorcery 1.5.8 with Forge 14.21.1.2404 - same. Cursor disappears when leaving telescope view (both ways).

**Comment by Doomgull** [comment] 2017-07-10 11:56
@AntonTrapp are you also using a Mac?

**Comment by AntonTrapp** [comment] 2017-07-10 14:49
Yes.

**Comment by swoolcock** [comment] 2017-09-02 01:58
I can confirm this bug exists in Astral Sorcery 1.6.1 in Modern Skyblock 2.  Running windowed mode on macOS Sierra 10.12.6.

I managed to find a reproducible way of fixing it without having to restart Minecraft.
With any GUI open (inventory, menu, furnace, etc.) move your cursor outside the window and over one of the items in the macOS dock.  Cursor magically reappears in Minecraft.  However, it will disappear again if you switch to another app and back.  :(

**Comment by cjburkey01** [comment] 2017-11-01 23:39
If you still have this issue, I found by using the Mac full screen and turning it off/on again returns the cursor.

**Comment by JaSpr** [comment] 2018-01-01 21:17
Still reproducing in OSX High Sierra in ATM Expert Remastered v1.1.1.  @cjburkey01's workaround works.

**Comment by kmork1** [comment] 2018-01-13 14:55
As: 1.12.2-1.8.4
Mc:1.12.2
Forge: 14.23.1.2566
Direwolf20 1.12 pack v 1.4
It’s the minecraft cursor disappearing during and after the Attunement. The only way to get my cursor back is to close my minecraft completely and restart it.

**Comment by Febilian** [comment] 2018-07-25 19:37
For anyone still having annoyances with this, I've found a workaround that allows me to keep playing.

It seems to be a Mac hardware issue for sure, that AS happens to cause.

Fixes from here have worked for me:

http://osxdaily.com/2013/07/19/disappearing-mouse-cursor-mac-os-x/

More specifically I just open the force quit menu, select it so that the Minecraft window has been de-selected from focus, then close the force quit menu without doing anything and go back to Minecraft and I get my cursor back.

**Comment by SiliconEnt** [comment] 2019-06-16 23:03
An easier workaround (works for Mojave at least) is to open your inventory, move the cursor to the top of the display, and click on the menu bar. The cursor reappears without ever having to pause the game.

**Comment by fakehero12211101** [comment] 2019-08-05 19:52
I'm playing with macOS 10.14.5, and trying to use the force quit menu to make the cursor reappear crashes the game instantly. What does work is going into Video Settings and toggling Fullscreen. This works for at least the Looking Glass. In addition, I can avoid the risk of making my cursor vanish by holding Shift (so that cursor is visible) then pressing Esc to exit the Looking Glass/Sextant/Telescope

**Comment by dajeff9001** [comment] 2019-08-24 15:37
I am running Astral on macOS 10.13.6. The mouse cursor problem used to apply with the Looking Glass for me, but the problem was solved when I clicked on Chrome and back. However, when I use the Observatory, I cannot get the mouse cursor to reappear on Minecraft in any way besides closing and restarting Minecraft. The cursor only disappears on the Minecraft tab, and clicking out and in does not work.

**Comment by swoolcock** [comment] 2020-01-23 22:25
Does this still happen in Forge 1.14?  If so I think #1188 is the best we're going to get for now, as Forge are no longer accepting submissions for 1.12.

**Comment by HellFirePvP** [comment] 2020-01-24 15:59
Indeed this issue will cease to be one come 1.14.
Input handling is now done differently so this won't cause issues anymore fortunately.

I'll potentially do _another_ 1.12 build then with 1188 included.

**Comment by HellFirePvP** [comment] 2020-01-31 19:05
The mentioned fix from swoolcock will be released in version 1.10.22
Feedback if that actually improved the situation or not is appreciated.

**Comment by swoolcock** [comment] 2020-02-03 04:51
Can confirm that this is fixed.

**Closed** 2020-04-05 16:55 UTC
Labels: OS/Hardware specific, bug
