### ISSUE TITLE
[1.16.4] Mineralis Ritual Ore Config Doesn't Work

### ISSUE THREAD

**Issue by NielsPilgaard** [HellFirePvP/AstralSorcery#1611] opened 2020-12-30 21:30 UTC
Adding Ores to the `mineralis_ritual_ore` config doesn't do anything, the ores that generate remain vanilla only.
Tested in an instance with only Astral Sorcery, Observerlib, Building Gadgets & Emendatus Enigmatica, which adds a truckload of ores.

Config: https://gist.github.com/NillerMedDild/f57f04b78cac9c2abbe8d36f431243d3

### Versions
Forge-1.16.4-35.1.28
astralsorcery-1.16.4-1.13.8
observerlib-1.16.4-1.4.4

**Comment by HellFirePvP** [comment] 2020-12-31 08:38
I'm afraid i cannot reproduce this..?
Same configs, using latest EmEn on curseforge, its alpha version, leading to this result:
![image](https://user-images.githubusercontent.com/7419378/103402091-e5810380-4b4b-11eb-9d36-d1a771d84da7.png)
exclusively EmEn ores

**Comment by NielsPilgaard** [comment] 2020-12-31 10:04
That's because they're a part of the tags the base config has. Only iron, gold, coal, redstone, lapis, emerald and diamond spawn, no matter what the config says.

**Comment by HellFirePvP** [comment] 2020-12-31 11:47
Interesting, sorry i misread the first report of this and now after analysis in code, it seems the 'additional' tags such as aluminum and bitumen and stuff isn't in the list of "all block tags" which i check when reading the config.
Somewhat concerning as it seems some data doesn't get transfered into that when those tags get read. I'll further investigate but am confident a fix can be added for 1.13.9

**Comment by HellFirePvP** [comment] 2020-12-31 11:55
Fixed for 1.13.9, a different way of resolving tags is now added.

**Comment by NielsPilgaard** [comment] 2020-12-31 13:32
> Interesting, sorry i misread the first report of this and now after analysis in code, it seems the 'additional' tags such as aluminum and bitumen and stuff isn't in the list of "all block tags" which i check when reading the config.

No worries, I wasn't clear tbh :P

> Fixed for 1.13.9, a different way of resolving tags is now added.

Thanks!

Is this based on block or item tags by the way?

**Comment by HellFirePvP** [comment] 2020-12-31 13:41
Block tags

**Comment by joshuap2005** [comment] 2020-12-31 21:48
I am having the same issue with astral sorcery on 1.12.2 (Direwolf 1.12.2 modpack), the mod is up to date. 
Config: https://github.com/joshuap2005/AstralSorceryConfigFile.git
Let me know if I did anything wrong in adding to the config
(I have no clue how to use github so i don't know if that link works properly)

**Comment by PocketfulOfGeese** [comment] 2020-12-31 22:23
"thaumcraft:ore_quartz" isn't an oredictionary entry, which is required for 1.12. Not related.

**Comment by joshuap2005** [comment] 2020-12-31 23:23
Doomgull, thats not the only one though. There were other ones added that still do not work

**Comment by PocketfulOfGeese** [comment] 2020-12-31 23:30
Did you actually create those oredict tags, though? oredicts don't get created natively unless the mod adding the material creates them, and several of those do not have a tag created by the originating mod by default.

And, again, different system. Probably should go to the Discord for more direct assistance with customer configuration setups, because it's not the same as this 1.16 issue. It would also be good to list the specific AS version and forge version involved when you do.

**Comment by joshuap2005** [comment] 2020-12-31 23:33
I did not create those oredict tags, and I also don't know how to. If you haven't been able to tell already i'm not very knowledgeable on this stuff. Do you have an invite to that discord so I can try that?

**Comment by PocketfulOfGeese** [comment] 2020-12-31 23:34
On the main page here on the github, and also on the curseforge page.

**Comment by joshuap2005** [comment] 2021-01-01 02:19
ok thanks

**Closed as completed** 2021-01-02 19:35 UTC
Labels: Type: Bug, Resolution: Fixed/Added next update, Version: 1.16.X
