### ISSUE TITLE
CTD on Dimension change to Galacticraft:Mars

### ISSUE THREAD

**Issue by midorlo** [HellFirePvP/AstralSorcery#606] opened 2018-03-26 19:46 UTC
https://pastebin.com/raw/RNME3U8R

Suprisingly, this is in fml-junk-earlystartup. There is no crash report. 

Client setup:
https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2531905

Win10x64,J8, softwares on current stable channel patch levels

Galacticraft, ExtraPlanets manually updated to current stables, optifine with sane (as possible) settings.

Note that after restarting the client, the crash not not (yet) occur again. I'll add more data as they happen.

**Comment by Doomgull** [comment] 2018-03-26 20:58
Looks like the cache was busted, might be related to 513, might not be.

Let me know if it replicates again.

**Comment by HellFirePvP** [comment] 2018-04-14 09:08
Falls into the same "category"/reason as #513 - marking this as duplicate since the causes are both the same.

**Closed by HellFirePvP** 2018-04-14 09:08 UTC
Labels: bug
