### ISSUE TITLE
[1.16.4]Went to attune myself and it crashed, now my world crashes every time I load in.

### ISSUE THREAD

**Issue by Eivaan** [HellFirePvP/AstralSorcery#1667] opened 2021-01-22 07:11 UTC
It probably is an issue with crashing on attuning yourself, and since I'm in the same spot It just picks me up to attune me and crashes I guess?
[Crash_Report.txt](https://github.com/HellFirePvP/AstralSorcery/files/5854101/Crash_Report.txt)

**Comment by Jeuvke** [comment] 2021-01-22 10:12
Duplicate of #1594.
TL;DR: it's Traveller's Index's fault

**Closed as completed** 2021-01-22 14:11 UTC
Labels: Resolution: duplicate
