### ISSUE TITLE
[1.15] ritual not working

### ISSUE THREAD

**Issue by M4TTI4** [HellFirePvP/AstralSorcery#1355] opened 2020-08-20 16:05 UTC
In the current latest 1.15 version of the mod not all the rituals are working. The following constellation crystals won't work when on pedestals:
Bootes
Armara
Octans
Mineralis

**Comment by HellFirePvP** [comment] 2020-08-29 09:45
I am unable to reproduce any of this behavior.

**Comment by HellFirePvP** [comment] 2020-08-29 12:24
So some things have crept up now that i've tested this more thorougly. So at least Evorsio and Horologium effects had an issue; i'll go through most things to add more clarifying particles and other things while i'm at it.

**Comment by HellFirePvP** [comment] 2020-08-29 16:02
I indeed did find quite a couple of things... well, those will be fixed for 1.12.8.

**Closed** 2020-08-29 17:59 UTC
Labels: Fixed/Added next update, bug
