### ISSUE TITLE
Crash with ItemArchitectWand MC 1.16

### ISSUE THREAD

**Issue by flece** [HellFirePvP/AstralSorcery#1679] opened 2021-01-27 18:08 UTC
Crash Report:
https://pastebin.com/VSxXu5Jg

Formation Wand with Grass Block pointing at Storage Drawers crasht the Client.

Good luck

**Comment by Jeuvke** [comment] 2021-01-27 18:16
Duplicate of #1418.

**Comment by flece** [comment] 2021-01-27 22:59
as mentioned...its already reported.

**Closed as completed** 2021-01-27 22:59 UTC
