### ISSUE TITLE
Starlight Crafting Visual and Audio Repeating

### ISSUE THREAD

**Issue by echohunter221** [HellFirePvP/AstralSorcery#1817] opened 2021-05-29 23:29 UTC
When crafting with the altar and infuser, the visuals and sound will keep repeating even after the crafting has finished. On minecraft version 1.16.5, Astral Sorcery version 1.13.11, forge version 36.1.24. Breaking the altar or re-entering the world fixes it. The completion sound also still happens. 

![2021-05-29_19 20 42](https://user-images.githubusercontent.com/11684647/120087090-0aee4b00-c0b3-11eb-8276-e66559c5194d.png)

https://user-images.githubusercontent.com/11684647/120087066-d5e1f880-c0b2-11eb-99c5-155d88eb77d6.mp4

979-785ac6077ce9.mp4

**Comment by HellFirePvP** [comment] 2021-05-30 08:25
Check your logs, probably duplicate of #1816

**Comment by nmills3** [comment] 2021-05-30 08:36
Can confirm, same issue here.

**Comment by nmills3** [comment] 2021-05-30 08:45
This issue also seems to happen with other effects in the mod. for example, i broke a celestial collector crystal but it's effect is still showing
![image](https://user-images.githubusercontent.com/26787639/120098070-c5219900-c12b-11eb-853a-8b9215918193.png)

**Comment by echohunter221** [comment] 2021-05-30 12:45
I believe it's a different issue. First of all, no crash, second of all here's the section of relevant log. https://pastebin.com/eQcywK2f Note that this also happens with astral sorcery alone, it's not a mod conflict in the pack I'm using. I'll get the log of the base astral world as well if you need it.

**Comment by nmills3** [comment] 2021-05-30 14:07
I think he means the root cause of both issues are the same. because some of the things in your log are very similar to what caused my crash

**Closed as completed** 2021-05-30 19:16 UTC
Labels: Type: Bug, Resolution: duplicate, Version: 1.16.X
