### ISSUE TITLE
Lenses and prisms don't relay starlight starting in MC 1.16.5

### ISSUE THREAD

**Issue by flowz91** [HellFirePvP/AstralSorcery#1835] opened 2021-06-17 17:40 UTC
Current version - AstralSorcery-1.16.5-1.13.12

Screenshots are from the current release of ATM6, but I've also tested this with just AS in vanilla 1.16.5, to the same effect.

Directing starlight from a collector crystal with crystal or prism lenses, regardless of their quality, at iron ore to transmute it into starmetal ore does not work. Both the beam of light and the particle effect on the iron ore appear like normal, but the block never transforms.

Linking the ore directly to a collector crystal does work as expected. After some more testing, it looks like linking AS crafting tables does not work either, whether directly to a working collector crystal or with lenses. The starlight value is identical to another table without a link right next to it.

Lenses with AFAIK ideal stats:
<img width="166" alt="Screenshot 2021-06-17 174056" src="https://user-images.githubusercontent.com/86067862/122430341-cfe58600-cf93-11eb-83e5-0a546473bd45.png">

Initial setup:
collector crystal -> two lenses -> one iron ore block each
collector crystal -> three iron ore blocks directly
<img width="1829" alt="Screenshot 2021-06-17 174424" src="https://user-images.githubusercontent.com/86067862/122430346-d07e1c80-cf93-11eb-91bc-ec769f6973f9.png">

Three directly linked blocks transform almost instantly even at noon, single blocks connected to lenses never do. 
A full ingame day later:
<img width="1916" alt="Screenshot 2021-06-17 180036" src="https://user-images.githubusercontent.com/86067862/122432827-f4426200-cf95-11eb-9bfb-5beed40e9d67.png">

**Comment by PocketfulOfGeese** [comment] 2021-06-22 14:49
Unable to reproduce, both took <5 seconds to convert at mid-day:
![image](https://user-images.githubusercontent.com/12677933/122946379-50670680-d347-11eb-8860-a72da368e343.png)

Versions used for this:
AS 1.16.5-1.13.12
Curios 1.16.5-4.0.5.2
Observerlib 1.16.51.5.3
JEI 1.16.57.7.0.106
Forge 32.1.37

**Comment by flowz91** [comment] 2021-06-22 15:41
After reproducing your setup exactly, it still doesn't work. 

![2021-06-22_17 36 45](https://user-images.githubusercontent.com/86067862/122955894-d18ebf80-d380-11eb-8697-2faf041ee280.png)

Forge 32.1.37 is not an available version as far as I can tell, using the versions listed on the AstralSorcery-1.16.5-1.13.12.jar
 file page. 

<img width="704" alt="Screenshot 2021-06-22 173843" src="https://user-images.githubusercontent.com/86067862/122955937-db182780-d380-11eb-97d6-6f470bcc30e0.png">

**Comment by PocketfulOfGeese** [comment] 2021-06-22 15:45
That is because I derped and loaded the 1.16.4 instance. Able to repro with Forge 36.x.x.

**Comment by Jeuvke** [comment] 2021-07-09 20:35
It appears that lenses do not transfer any starlight at all.

**Comment by PocketfulOfGeese** [comment] 2021-07-16 16:35
This issue began with 1.16.5 MC, 1.13.9 AS transferred just fine. Forge version does not appear to impact this as long as at least the minimum version necessary to run the mod.

**Comment by dan96kid** [comment] 2021-09-26 02:04
I can confirm that I'm having this issue. Modpack is ATM 6
![image](https://user-images.githubusercontent.com/14021093/134790664-28f824c3-d46f-495f-904e-b50d1729e1a3.png)

**Comment by WebDragon** [comment] 2021-10-30 06:04
Just ran smack into this in the latest Direwolf20 modpack from FTB as well

**Comment by Aeonsteel** [comment] 2021-11-18 22:08
I would like to confirm that Colored Lenses still work as intended (Even ones like Growth and Break). You cannot chain lenses or transmute from a lens, though.

**Comment by cosmosgenius** [comment] 2021-12-11 16:41
Just encountered this in enigmatic 6. The pumpkin to cake only works directly with Crystal but not via prism

**Comment by Timelife** [comment] 2022-02-02 05:24
Same here, playing ATMS and the pumpkin transmutation does not occur unless directly connected to collector, the pumpkins just sparkle. Additionally, light does not appear to chain through lenses and prisms after the first lens or prism.

**Comment by Omega4451** [comment] 2022-03-03 20:30
Is there any progress being made on this? does the mod creator know about this yet? this basically makes the mod almost unplayable.

**Comment by PocketfulOfGeese** [comment] 2022-03-03 22:04
The mod creator knows, that's why it's here. Real life takes precedence over a hobby project.

And no, it literally does not do that. Nothing in the mod in inaccessible with this issue, it just impacts potential aesthetic build layout.

**Comment by Omega4451** [comment] 2022-03-03 22:27
Okay... i should rephrase, because you are correct, it does make it impossible to condense things in a single base easily and it makes crossover with other mods extremely difficult if not impossible, I apologize for my overuse of the word there.

**Closed as completed** 2022-05-31 20:39 UTC
Labels: Type: Bug, Resolution: Fixed/Added next update, Version: 1.16.X
