### ISSUE TITLE
Collector Crystal destroyed by Celestial Crystal Cluster formation

### ISSUE THREAD

**Issue by Morat2255** [HellFirePvP/AstralSorcery#1684] opened 2021-01-30 06:48 UTC
I was making celestial crystal clusters, throwing the crystal and stardust into a 1 block pool of liquid starlight. I had the liquid starlight directly adjacent to my collector crystal, to make sure it had easy line of sight to both the starmetal ore and the crystal cluster. But one of the items I dropped in must have landed just over the line into the blockspace of the collector crystal, and when the crystal cluster formed, it formed in the wrong block, and instead of overwriting and deleting the liquid starlight, it instead overwrote and deleted the collector crystal.

I'm on the current Direwolf20 1.16 pack
My mod version is Astral Sorcery 1.16.4-1.13.9

**Comment by Jeuvke** [comment] 2021-01-30 12:38
Duplicate of #1618

**Closed as completed** 2021-02-04 16:26 UTC
Labels: Resolution: duplicate, Version: 1.16.X
