### ISSUE TITLE
Crafting recipes unavailable unless open/close journal 

### ISSUE THREAD

**Issue by Electrofried** [HellFirePvP/AstralSorcery#130] opened 2017-04-22 09:54 UTC
Having an issue where the crafting table (all versions) sometimes stops listing the output of a recipe and will not function until a user opens the journal again to refresh something, then the crafting will work again.

**Comment by HellFirePvP** [comment] 2017-04-22 10:25
Try replicating this with only AS on its latest version and Forge. If it doesn't happen anymore, do a world backup, try removing mods and see when it stops happening. Preferably mods that manipulate the vanilla crafting table GUI.

**Comment by HellFirePvP** [comment] 2017-04-27 09:28
Any information on this? The journal is not connected to anything crafting related and *i* don't refresh anything if you open/close the journal.

**Comment by Electrofried** [comment] 2017-04-27 09:46
Removed this mod [https://mods.curse.com/mc-mods/minecraft/237414-realbench]('real bench') as it was also interfearing with other non Astral Sorcery crafting table recipes and the issue seems to be gone. Sorry forgot to update you.  

Still getting a strange issue where the crafting altars do not detect a valid recipe and show the output at times unless you remove and replace certain items in the grid but I will open a separate issue on that if I can track down some more information on the issue that is valid.

**Comment by HellFirePvP** [comment] 2017-04-27 09:52
For future reference on realbench: #123 

For the altar issue, be sure that you have enough starlight & that it fulfills its conditions described in the book. For example certain things may only be crafted during nighttime or w/e and it'll then not show the output during daytime for example.

**Comment by HellFirePvP** [comment] 2017-05-07 10:41
"Removed this mod (...) and the issue seems to be gone."

There was no more information provided on the other subject, so i assume it was either correct from what i guessed or you couldn't reproduce it anymore?... Either way, if something regarding this comes up again, feel free to open another issue or reopen this one. Closing it for now.

**Closed by HellFirePvP** 2017-05-07 10:41 UTC
Labels: bug, mod interaction
