### ISSUE TITLE
[1.16.5] Lens use bug

### ISSUE THREAD

**Issue by GoogeTan** [HellFirePvP/AstralSorcery#1876] opened 2021-08-17 13:50 UTC
If I connect flying crystal to the lens, the game crashes with:
https://pastebin.com/MiRWyAED
The world becomes broken and I got this error every world load.

**Comment by PocketfulOfGeese** [comment] 2021-08-17 13:53
Looks like your lens has a bad NBT value, will need to use something like worldedit to remove the lens. How did you get the lens? How did you place it? Did you use something like building gadgets or the like on it at some point, which will strip the NBT?

**Comment by GoogeTan** [comment] 2021-08-17 14:04
I crafted it and placed it by hand

**Comment by PocketfulOfGeese** [comment] 2021-08-17 14:35
What pack, and what recipe? Not able to reproduce that normally.

**Comment by Jeuvke** [comment] 2021-08-17 14:36
> Looks like your lens has a bad NBT value, will need to use something like worldedit to remove the lens.

Removing the lens won't stop the crashing, since the starlight network doesn't get updated.

**Comment by PocketfulOfGeese** [comment] 2021-08-17 15:02
Still has to be removed. If it still crashes on start AFTERWARD, will need to trigger the "rebuild starlight network" server config file option.

**Comment by Jeuvke** [comment] 2021-08-17 15:05
You can also just delete the starlight network for the chunk the lens is in. You don't need to edit out the lens that way.

**Comment by GoogeTan** [comment] 2021-08-17 19:15
> 
> 
> What pack, and what recipe? Not able to reproduce that normally.

My own. Ther is mods list: https://pastebin.com/A6fbTaVi

**Comment by PocketfulOfGeese** [comment] 2021-09-18 16:28
To wrap this up and close it out: the NBT was stripped off the lens somehow. BuidlingGadgets is a common instance of seeing this, which can cause this.

**Closed as completed** 2021-09-18 16:29 UTC
Labels: Resolution: Not my Mod/Won't Fix, Version: 1.16.X
