### ISSUE TITLE
Quit to Title breaks Starlight Transmutation

### ISSUE THREAD

**Issue by SciFiz** [HellFirePvP/AstralSorcery#535] opened 2018-01-28 15:17 UTC
I don't have a server to test it with, but in single player starlight transmution will not work, and even stop part way through if you quit to title screen then load back into any world. The light beam shows but the particle effects don't appear and the change doesn't occur. Rebooting minecraft will fix it.

The iron ore block I was testing with was placed by the player, not any kind of automation.

AS version: 1.8.5
pack: DW20 1.12 v1.8.0
java: 1.8.0 161 (manually changed in launcher)

**Comment by Doomgull** [comment] 2018-01-28 19:24
Can you provide the server-side log for the SSP instance, both from when exiting, and then when loading back in to view the transmutation broken? Sounds like something's not properly unloading/reloading unless the pack restarts.

**Comment by HellFirePvP** [comment] 2018-01-28 20:35
in addition to that, try reproducing this without any chunkloading mods installed.

**Comment by SciFiz** [comment] 2018-01-29 19:03
I'm going to assume this is the appropriate log since it's the only one I can find that looks to be relevant. 
Part 1: https://pastebin.com/rJxtVkp5
Part 2: https://pastebin.com/CQv2N7uy

**Comment by psychofad** [comment] 2018-02-02 00:54
We are noticing this same issue on a multiplayer server.  The server is set up so no Astral Sorcery structures spawn in the overworld, forcing the player to venture into an the Earth dimension in the Elemental Dimensions mod by McJty to find those structures, the primary crafting experience of making your first wand and making a luminous crafting table goes off without a hitch, but once you get into transmutation to get starmetal this is where we run into issues.  If you happen to log out in the Earth dimension before a server restart, when the server comes back up you are able to transmute to your hearts content, howver if you venture back to the overworld and then come back, well, no more transmutation until a server restart.  Upon further testing, if you happen to bring a chunk loader with you and place it down before leaving the earth dimension, upon returning you are still able to transmute.

So it appears that when the dimension unloads after you leave the first time, something is not happening properly when you return to allow the transmutation.  Chuck loading, of course, prevents the dimension from unloading, thus you can transmute as you should be.

I am not the server owner, so I do not have access to any logs, but this seems to be a problem with Astral Sorcery not loading things properly after the dimension reloads.

**Comment by psychofad** [comment] 2018-02-02 00:56
The server owner said he can provide any additional info you may need

**Comment by Doomgull** [comment] 2018-02-02 00:57
Which mod's chunkloader?

**Comment by kwpugh** [comment] 2018-02-02 00:58
Hi,

I'm the server for above comment, he is the basics:

Forge: forge-1.12.2-14.23.1.2608
Mods: astralsorcery-1.12.2-1.8.5.jar and elementaldimensions-1.12-0.2.0.jar 

Please let me know if you need server logs and which ones.

Regards.

**Comment by psychofad** [comment] 2018-02-02 01:07
weirding gadget is the chunk loader mod

**Comment by kwpugh** [comment] 2018-02-02 01:21
Here is a link to the modpack with the full list of mods.

https://minecraft.curseforge.com/projects/pughland-foedare

**Comment by Johnyknowhow** [comment] 2018-03-03 04:05
This issue is occurring with the FTB Revelation v1.6.0 modpack as well.

**Comment by bonnedav** [comment] 2018-03-06 03:03
I am having this problem as well.

**Comment by InThayne** [comment] 2018-04-09 21:08
Same problem here

**Comment by HellFirePvP** [comment] 2020-01-31 19:04
Actually finally found the issue for this being related to how data regarding the starlight network is written & read. Unfortunately i won't rewrite the entire section for this for 1.12, but as far as the 1.14 version goes it should be fixed from thereon.

**Comment by HellFirePvP** [comment] 2020-06-02 19:12
So. yea. closing this as it won't be addressed from my end for 1.12, will be by-design fixed with the 1.14 internal changes.

**Closed by HellFirePvP** 2020-06-02 19:12 UTC
Labels: 1.12-Only, bug
